// <auto-generated />
using System;
using Demo02.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Demo02.Migrations.WarehouseDb
{
    [DbContext(typeof(WarehouseDbContext))]
    partial class WarehouseDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Demo02.Models.DimGuest", b =>
                {
                    b.Property<Guid>("GuestKey")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("GuestType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LoyaltyTier")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nationality")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("GuestKey");

                    b.ToTable("DimGuests");
                });

            modelBuilder.Entity("Demo02.Models.DimRoom", b =>
                {
                    b.Property<Guid>("RoomKey")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("BasePrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Floor")
                        .HasColumnType("int");

                    b.Property<string>("RoomNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TypeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RoomKey");

                    b.ToTable("DimRooms");
                });

            modelBuilder.Entity("Demo02.Models.FactReservation", b =>
                {
                    b.Property<Guid>("ReservationKey")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("ADR")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ChannelName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("DateKey")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("GuestKey")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Nights")
                        .HasColumnType("int");

                    b.Property<decimal>("Revenue")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("RoomKey")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ReservationKey");

                    b.ToTable("FactReservations");
                });
#pragma warning restore 612, 618
        }
    }
}
